# Generated by Django 5.0.2 on 2024-02-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url_field',
            field=models.URLField(default='new'),
            preserve_default=False,
        ),
    ]
